force-app/main/default/objects/TriggerFeature__mdt/TriggerFeature__mdt.object-meta.xml
<CustomObject>
    <description>Registers a feature for execution in trigger contexts (before insert, after insert, etc). Only active controls are executed.</description>
    <label>Trigger Feature</label>
    <pluralLabel>Trigger Features</pluralLabel>
</CustomObject>

force-app/main/default/objects/TriggerFeature__mdt/fields/AfterDelete__c.field-meta.xml
<CustomField>
    <fullName>AfterDelete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Runs this handler in &quot;after delete&quot; context.</description>
    <inlineHelpText>Runs the handler in &quot;after delete&quot; context.</inlineHelpText>
    <label>After Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerFeature__mdt/fields/AfterInsert__c.field-meta.xml
<CustomField>
    <fullName>AfterInsert__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Runs this handler in &quot;after insert&quot; context.</description>
    <inlineHelpText>Runs the handler in &quot;after insert&quot; context.</inlineHelpText>
    <label>After Insert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerFeature__mdt/fields/Asynchronous__c.field-meta.xml
<CustomField>
    <fullName>Asynchronous__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Asynchronous</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerFeature__mdt/fields/BeforeInsert__c.field-meta.xml
<CustomField>
    <fullName>BeforeInsert__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Runs this handler in &quot;before insert&quot; context.</description>
    <inlineHelpText>Runs the handler in &quot;before insert&quot; context.</inlineHelpText>
    <label>Before Insert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerFeature__mdt/fields/BeforeUpdate__c.field-meta.xml
<CustomField>
    <fullName>BeforeUpdate__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Runs this handler in &quot;before update&quot; context.</description>
    <inlineHelpText>Runs the handler in &quot;before update&quot; context.</inlineHelpText>
    <label>Before Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerFeature__mdt/fields/Handler__c.field-meta.xml
<CustomField>
    <fullName>Handler__c</fullName>
    <description>The exact class name of the handler that implements the ITriggerExecutable interface. Set the fully qualified name, if a subclass implements the interface.</description>
    <inlineHelpText>Set the apex class name of the handler that will run in the specified contexts.</inlineHelpText>
    <label>Handler</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TriggerFeature__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Activates the handler for processing.</description>
    <inlineHelpText>Activates the handler. Inactive handlers are only executed with the forceActivateFeature API.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerFeature__mdt/fields/LoadOrder__c.field-meta.xml
<CustomField>
    <fullName>LoadOrder__c</fullName>
    <description>The order of execution for this specific handler. The order is in relation to other triggers on the same object with the same Trigger Actions, for example, all “before insert” triggers on Account.</description>
    <inlineHelpText>The order of execution for this specific handler. The order is in relation to other triggers on the same object with the same Trigger Actions, for example, all “before insert” triggers on Account.</inlineHelpText>
    <label>Load Order</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TriggerFeature__mdt/fields/SObjectName__c.field-meta.xml
<CustomField>
    <fullName>SObjectName__c</fullName>
    <description>The name of the object the class should act on, for example, Account, Contact, Opportunity.</description>
    <inlineHelpText>Set the SObject where the handler is executed. The SObject must implement a trigger that calls the framework.</inlineHelpText>
    <label>SObject Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TriggerHandlerTest.cls
/**
 * Created by vncasolns on 2024-02-01.
 */
@IsTest
public with sharing class TriggerHandlerTest {

    @IsTest
    static void testAccounts() {
        setupAccountMockFeatures();

        List<Account> accounts = getAccounts();
        insert accounts;

        accounts = [SELECT Id, AccountNumber, Description FROM Account WHERE Id IN :accounts];
        for (Account account : accounts) {
            System.assertEquals('Account created', account.Description);
        }
        List<Contact> contacts = [SELECT Id FROM Contact WHERE AccountId IN :accounts];
        System.assertEquals(3, contacts.size());

        for (Account account : accounts) {
            account.Type = 'Other';
        }
        update accounts;
        accounts = [SELECT Id, Industry FROM Account WHERE Id IN :accounts];
        for (Account account : accounts) {
            System.assertEquals('Other', account.Industry);
        }

        Test.startTest();
        delete accounts;
        Test.stopTest();

        contacts = [SELECT Id FROM Contact WHERE AccountId IN :accounts];
        System.assertEquals(0, contacts.size());
    }

    @IsTest
    static void testFeatureDoesNotExist() {
        List<TriggerFeature__mdt> mocks = new List<TriggerFeature__mdt>();
        mocks.add(
            new TriggerFeature__mdt(
                DeveloperName = 'FeatureDoesNotExist',
                Handler__c = 'TriggerHandlerTest.FeatureDoesNotExist',
                SObjectName__c = 'Account',
                IsActive__c = true,
                LoadOrder__c = 10,
                BeforeInsert__c = true
            )
        );
        TriggerHandler.setMocks('Account', mocks);

        List<Account> accounts = getAccounts();
        Boolean expectedExceptionThrown = false;
        try {
            insert accounts;
            System.assert(false);
        } catch (Exception e) {
            expectedExceptionThrown = true;
        }
        System.assertEquals(expectedExceptionThrown, true);
    }

    @IsTest
    static void testInvalidFeature() {
        List<TriggerFeature__mdt> mocks = new List<TriggerFeature__mdt>();
        mocks.add(
            new TriggerFeature__mdt(
                DeveloperName = 'InvalidFeature',
                Handler__c = 'TriggerHandlerTest.InvalidFeature',
                SObjectName__c = 'Account',
                IsActive__c = true,
                LoadOrder__c = 10,
                BeforeInsert__c = true
            )
        );
        TriggerHandler.setMocks('Account', mocks);

        List<Account> accounts = getAccounts();
        Boolean expectedExceptionThrown = false;
        try {
            insert accounts;
            System.assert(false);
        } catch (Exception e) {
            expectedExceptionThrown = true;
        }
        System.assertEquals(expectedExceptionThrown, true);
    }

    public class AccountAddDescription implements ITriggerExecutable {
        public void execute(TriggerContext context) {
            for (Account account : (List<Account>) context.getPrimaryList()) {
                if (context.beforeInsert()) {
                    account.Description = 'Account created';
                }
            }
        }
    }

    public class AccountCreateContact implements ITriggerExecutable {
        public void execute(TriggerContext context) {
            List<Contact> contacts = new List<Contact>();
            for (Account account : (List<Account>) context.getPrimaryList()) {
                if (context.afterInsert()) {
                    contacts.add(new Contact(AccountId = account.Id, LastName = account.Name));
                }
            }
            insert contacts;
        }
    }

    public class AccountUpdateIndustry implements ITriggerExecutable {
        public void execute(TriggerContext context) {
            for (Account vAccount : (List<Account>) context.getPrimaryList()) {
                if (context.isChanged(vAccount, Account.Type) && vAccount.Type == 'Other') {
                    vAccount.Industry = 'Other';
                }
            }
        }
    }

    public class DeleteContactsAsync implements ITriggerExecutable {
        public void execute(TriggerContext context) {
            if (!context.afterDelete()) {
                return;
            }
            List<Contact> contacts = [SELECT Id FROM Contact WHERE AccountId IN :context.getRecordIds()];
            if (!contacts.isEmpty()) {
                delete contacts;
            }
        }
    }

    public class InvalidFeature {
        public void execute(TriggerContext context) {
            for (Account account : (List<Account>) context.getPrimaryList()) {
                account.Description = 'Account created';
            }
        }
    }

    private static void setupAccountMockFeatures() {
        List<TriggerFeature__mdt> mocks = new List<TriggerFeature__mdt>();
        mocks.add(
            new TriggerFeature__mdt(
                DeveloperName = 'AccountAddDescription',
                Handler__c = 'TriggerHandlerTest.AccountAddDescription',
                SObjectName__c = 'Account',
                IsActive__c = true,
                LoadOrder__c = 10,
                BeforeInsert__c = true
            )
        );
        mocks.add(
            new TriggerFeature__mdt(
                DeveloperName = 'AccountCreateContact',
                Handler__c = 'TriggerHandlerTest.AccountCreateContact',
                SObjectName__c = 'Account',
                IsActive__c = true,
                LoadOrder__c = 20,
                AfterInsert__c = true
            )
        );
        mocks.add(
            new TriggerFeature__mdt(
                DeveloperName = 'AccountUpdateIndustry',
                Handler__c = 'TriggerHandlerTest.AccountUpdateIndustry',
                SObjectName__c = 'Account',
                IsActive__c = true,
                LoadOrder__c = 20,
                BeforeUpdate__c = true
            )
        );
        mocks.add(
            new TriggerFeature__mdt(
                DeveloperName = 'DeleteContactsAsync',
                Handler__c = 'TriggerHandlerTest.DeleteContactsAsync',
                SObjectName__c = 'Account',
                IsActive__c = true,
                LoadOrder__c = 40,
                AfterDelete__c = true,
                Asynchronous__c = true
            )
        );
        TriggerHandler.setMocks('Account', mocks);
    }

    private static List<Account> getAccounts() {
        List<Account> accounts = new List<Account>();
        accounts.add(new Account(Name = 'Test1', BillingCity = 'Toronto', AccountNumber = '123', Industry = 'Technology'));
        accounts.add(new Account(Name = 'Test2', BillingCity = 'Calgary', AccountNumber = '456', Industry = 'Technology'));
        accounts.add(new Account(Name = 'Test3', BillingCity = 'Vancouver', AccountNumber = '789', Industry = 'Technology'));
        return accounts;
    }
}