force-app/main/default/objects/TriggerFeature__mdt/TriggerFeature__mdt.object-meta.xml
<CustomObject>
    <description>Registers a feature for execution in trigger contexts (before insert, after insert, etc). Only active controls are executed.</description>
    <label>Trigger Feature</label>
    <pluralLabel>Trigger Features</pluralLabel>
</CustomObject>

force-app/main/default/objects/TriggerFeature__mdt/fields/AfterInsert__c.field-meta.xml
<CustomField>
    <fullName>AfterInsert__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Runs this handler in &quot;after insert&quot; context.</description>
    <inlineHelpText>Runs the handler in &quot;after insert&quot; context.</inlineHelpText>
    <label>After Insert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerFeature__mdt/fields/AfterUpdate__c.field-meta.xml
<CustomField>
    <fullName>AfterUpdate__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Runs this handler in &quot;after update&quot; context.</description>
    <inlineHelpText>Runs the handler in &quot;after update&quot; context.</inlineHelpText>
    <label>After Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerFeature__mdt/fields/Asynchronous__c.field-meta.xml
<CustomField>
    <fullName>Asynchronous__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Asynchronous</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerFeature__mdt/fields/BeforeInsert__c.field-meta.xml
<CustomField>
    <fullName>BeforeInsert__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Runs this handler in &quot;before insert&quot; context.</description>
    <inlineHelpText>Runs the handler in &quot;before insert&quot; context.</inlineHelpText>
    <label>Before Insert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerFeature__mdt/fields/BeforeUpdate__c.field-meta.xml
<CustomField>
    <fullName>BeforeUpdate__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Runs this handler in &quot;before update&quot; context.</description>
    <inlineHelpText>Runs the handler in &quot;before update&quot; context.</inlineHelpText>
    <label>Before Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerFeature__mdt/fields/Handler__c.field-meta.xml
<CustomField>
    <fullName>Handler__c</fullName>
    <description>The exact class name of the handler that implements the ITriggerExecutable interface. Set the fully qualified name, if a subclass implements the interface.</description>
    <inlineHelpText>Set the apex class name of the handler that will run in the specified contexts.</inlineHelpText>
    <label>Handler</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TriggerFeature__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Activates the handler for processing.</description>
    <inlineHelpText>Activates the handler. Inactive handlers are only executed with the forceActivateFeature API.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerFeature__mdt/fields/LoadOrder__c.field-meta.xml
<CustomField>
    <fullName>LoadOrder__c</fullName>
    <description>The order of execution for this specific handler. The order is in relation to other triggers on the same object with the same Trigger Actions, for example, all “before insert” triggers on Account.</description>
    <inlineHelpText>The order of execution for this specific handler. The order is in relation to other triggers on the same object with the same Trigger Actions, for example, all “before insert” triggers on Account.</inlineHelpText>
    <label>Load Order</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TriggerDispatcherTest.cls
/**
 * Created by sonal on 2024-09-27.
 */

@IsTest
public class TriggerDispatcherTest {
    @IsTest
    static void testAccountContactCreation() {
        List<TriggerFeature__mdt> mocks = new List<TriggerFeature__mdt>();
        mocks.add(
            new TriggerFeature__mdt(
                DeveloperName = 'TriggerDispatcherTestA',
                Handler__c = 'TriggerDispatcherTest.AccountUpdateAnnualRevenue',
                IsActive__c = true,
                LoadOrder__c = 10,
                BeforeInsert__c = true,
                BeforeUpdate__c = true
            )
        );
        mocks.add(
            new TriggerFeature__mdt(
                DeveloperName = 'TriggerDispatcherTestB',
                Handler__c = 'TriggerDispatcherTest.ContactCreateHandler',
                IsActive__c = true,
                LoadOrder__c = 20,
                AfterInsert__c = true,
                AfterUpdate__c = true
            )
        );
        TriggerDispatcher.setMockControls('Account', mocks);

        Account newAccount = new Account(
            Name = 'New Test Account',
            Industry = 'Finance',
            BillingCountry = 'Canada',
            BillingState = 'Ontario',
            AnnualRevenue = 0
        );

        Test.startTest();
        insert newAccount;

        List<Contact> contacts = [SELECT Id, Account.AnnualRevenue FROM Contact WHERE AccountId = :newAccount.Id];
        System.assertEquals(1, contacts.size());
        System.assertEquals(100000, contacts[0].Account.AnnualRevenue);

        newAccount.AnnualRevenue = 0;
        update newAccount;
        Test.stopTest();

        contacts = [SELECT Id, Account.AnnualRevenue FROM Contact WHERE AccountId = :newAccount.Id];
        System.assertEquals(2, contacts.size());
        System.assertEquals(200000, contacts[0].Account.AnnualRevenue);
    }

    @IsTest
    static void testAsyncMode() {
        List<TriggerFeature__mdt> mocks = new List<TriggerFeature__mdt>();
        mocks.add(
            new TriggerFeature__mdt(
                DeveloperName = 'TriggerDispatcherTestA',
                Handler__c = 'TriggerDispatcherTest.ContactCreateHandlerAsync',
                IsActive__c = true,
                LoadOrder__c = 20,
                AfterInsert__c = true,
                Asynchronous__c = true
            )
        );
        TriggerDispatcher.setMockControls('Account', mocks);

        Account newAccount = new Account(
            Name = 'New Test Account',
            Industry = 'Finance',
            BillingCountry = 'Canada',
            BillingState = 'Ontario',
            AnnualRevenue = 0
        );
        Test.startTest();
        insert newAccount;
        Test.stopTest();

        List<Contact> contacts = [SELECT Id FROM Contact WHERE AccountId = :newAccount.Id];
        System.assertEquals(1, contacts.size());
    }

    @IsTest
    static void testAsyncModeBefore() {
        List<TriggerFeature__mdt> mocks = new List<TriggerFeature__mdt>();
        mocks.add(
            new TriggerFeature__mdt(
                DeveloperName = 'TriggerDispatcherTestA',
                Handler__c = 'TriggerDispatcherTest.ContactCreateHandlerAsync',
                IsActive__c = true,
                LoadOrder__c = 20,
                BeforeInsert__c = true,
                Asynchronous__c = true
            )
        );
        TriggerDispatcher.setMockControls('Account', mocks);

        Account newAccount = new Account(
            Name = 'New Test Account',
            Industry = 'Finance',
            BillingCountry = 'Canada',
            BillingState = 'Ontario',
            AnnualRevenue = 0
        );
        Boolean exceptionFound = false;
        try {
            insert newAccount;
        } catch (Exception e) {
            exceptionFound = true;
        }

        System.assertEquals(true, exceptionFound);
    }

    @IsTest
    static void testTriggerMetrics() {
        List<TriggerFeature__mdt> accountMocks = new List<TriggerFeature__mdt>();

        accountMocks.add(
            new TriggerFeature__mdt(
                DeveloperName = 'TriggerDispatcherTestA',
                Handler__c = 'TriggerDispatcherTest.ContactCreateHandler',
                IsActive__c = true,
                LoadOrder__c = 20,
                AfterInsert__c = true,
                AfterUpdate__c = true
            )
        );
        TriggerDispatcher.setMockControls('Account', accountMocks);
        TriggerMetrics.enableMetrics();

        Account newAccount = new Account(
            Name = 'New Test Account',
            Industry = 'Finance',
            BillingCountry = 'Canada',
            BillingState = 'Ontario',
            AnnualRevenue = 0
        );

        Test.startTest();
        insert newAccount;

        Test.stopTest();

        List<Contact> contacts = [SELECT Id, FirstName FROM Contact WHERE AccountId = :newAccount.Id];
        System.assertEquals(1, contacts.size());
    }

    @IsTest
    static void testNonExistentClass() {
        List<TriggerFeature__mdt> mocks = new List<TriggerFeature__mdt>();
        mocks.add(
            new TriggerFeature__mdt(
                DeveloperName = 'TriggerDispatcherTestA',
                Handler__c = 'TriggerDispatcherTest.NonExistentClass',
                IsActive__c = true,
                LoadOrder__c = 10,
                BeforeInsert__c = true
            )
        );
        TriggerDispatcher.setMockControls('Account', mocks);

        Account newAccount = new Account(
            Name = 'New Test Account',
            Industry = 'Finance',
            BillingCountry = 'Canada',
            BillingState = 'Ontario',
            AnnualRevenue = 0
        );

        Boolean exceptionFound = false;
        try {
            insert newAccount;
        } catch (Exception e) {
            exceptionFound = true;
        }

        System.assertEquals(true, exceptionFound);
    }

    @IsTest
    static void testInvalidClass() {
        List<TriggerFeature__mdt> mocks = new List<TriggerFeature__mdt>();
        mocks.add(
            new TriggerFeature__mdt(
                DeveloperName = 'TriggerDispatcherTestA',
                Handler__c = 'TriggerDispatcherTest.InvalidClass',
                IsActive__c = true,
                LoadOrder__c = 10,
                BeforeInsert__c = true
            )
        );
        TriggerDispatcher.setMockControls('Account', mocks);

        Account newAccount = new Account(
            Name = 'New Test Account',
            Industry = 'Finance',
            BillingCountry = 'Canada',
            BillingState = 'Ontario',
            AnnualRevenue = 0
        );

        Boolean exceptionFound = false;
        try {
            insert newAccount;
        } catch (Exception e) {
            exceptionFound = true;
        }

        System.assertEquals(true, exceptionFound);
    }

    public class AccountUpdateAnnualRevenue implements ITriggerExecutable {
        public void execute(TriggerContext context) {
            for (Account acc : (List<Account>) context.getRecords()) {
                if (context.beforeInsert()) {
                    acc.AnnualRevenue += 100000;
                } else if (context.beforeUpdate() && context.isChanged(acc, Account.AnnualRevenue)) {
                    acc.AnnualRevenue += 200000;
                }
            }
        }
    }

    public class ContactCreateHandler implements ITriggerExecutable {
        public void execute(TriggerContext context) {
            List<Contact> contacts = new List<Contact>();
            for (Account acc : (List<Account>) context.getRecords()) {
                contacts.add(new Contact(LastName = acc.Name, AccountId = acc.Id));
            }
            insert contacts;
        }
    }

    public class ContactCreateHandlerAsync implements ITriggerExecutable {
        public void execute(TriggerContext context) {
            List<Contact> contacts = new List<Contact>();
            for (Id accountId : (Set<Id>) context.getRecordIds()) {
                contacts.add(new Contact(LastName = 'Demo', AccountId = accountId));
            }
            insert contacts;
        }
    }

    public class InvalidClass {
        public void execute(TriggerContext context) {
            Integer i = 1;
        }
    }
}